- name: Deploy Local Backend Code Safely
  hosts: backend
  become: true

  vars:
    app_user: roboshop
    local_backend_path: "/home/ec2-user/Contact-Manager/backend"
    app_dir: /app

    jwt_secret_key: "{{ lookup('env', 'JWT_SECRET_KEY') }}"
    mongo_cloud_url: "{{ lookup('env', 'MONGO_DB_CLOUD_URL') }}"
    mongo_database: "{{ lookup('env', 'MONGO_DB_DATABASE') }}"

  tasks:

    - name: Ensure roboshop user exists
      user:
        name: "{{ app_user }}"
        shell: /bin/bash
        create_home: yes

    # 游릭 Amazon Linux 2023 Node.js installation
    - name: Install Node.js 18 on AL2023
      package:
        name: nodejs-18*
        state: present

    # 游릭 Install PM2 globally
    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes
        state: present

    # 游릭 Ensure /app directory exists
    - name: Ensure /app directory exists
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0755"

    # 游릭 Copy backend code
    - name: Copy backend from local path to /app
      command: rsync -a --delete {{ local_backend_path }}/ {{ app_dir }}/
      become_user: "{{ app_user }}"

    # 游릭 Create .env file
    - name: Create backend .env file
      template:
        src: env.j2
        dest: "{{ app_dir }}/.env"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0600"

    # 游릭 Install dependencies
    - name: Install backend npm dependencies
      npm:
        path: "{{ app_dir }}"
        production: false
      become_user: "{{ app_user }}"

    # 游릭 Build TypeScript
    - name: Build TypeScript
      command: npx tsc
      args:
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}"

    # 游릭 Start or restart backend using PM2
    - name: Start or restart backend using PM2
      shell: |
        pm2 describe backend > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            pm2 restart backend --update-env
        else
            pm2 start dist/index.js --name backend
        fi
        pm2 save
      args:
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}"

