- name: Deploy backend from local folder
  hosts: backend
  become: true

  vars:
    app_user: roboshop
    app_dir: /app
    local_backend_path: /home/ec2-user/Contact-Manager/backend

  tasks:

    - name: Ensure roboshop user exists
      user:
        name: "{{ app_user }}"
        shell: /bin/bash
        create_home: yes

    - name: Add NodeSource repo for Node.js 18
      shell: curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -

    - name: Install Node.js and npm
      package:
        name: nodejs
        state: present

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes
        state: present

    - name: Ensure /app directory exists
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Set ownership of /app directory
      file:
        path: "{{ app_dir }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        recurse: yes

    - name: Copy backend code to server
      copy:
        src: /home/ec2-user/Contact-Manager/backend/
        dest: /app/
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: 0755
      become: true

    - name: Install npm dependencies
      command: npm install
      args:
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}"

    - name: Ensure TypeScript is installed locally
      npm:
        name: typescript
        path: "{{ app_dir }}"
        state: present
      become_user: "{{ app_user }}"

    - name: Build TypeScript to generate server.js
      command: npx tsc
      args:
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}"

    - name: Check if compiled server.js exists
      stat:
        path: "{{ app_dir }}/server.js"
      register: server_js_file

    - name: Start or restart backend using PM2
      shell: |
        pm2 describe backend > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            pm2 restart backend --update-env
        else
            pm2 start server.js --name backend
        fi
      args:
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}"
      when: server_js_file.stat.exists




