---
- name: Deploy Backend App
  hosts: backend
  become: true
  vars:
    backend_src_path: "/home/ec2-user/Contact-Manager/backend"
    app_dir: "/app"

  tasks:

    - name: Create /app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Install Node.js 18 on AL2023
      command: dnf install -y nodejs18

    - name: Install PM2 globally
      npm:
        name: pm2
        global: true
        executable: /usr/bin/npm

    - name: Copy backend to /app
      command: rsync -a --delete {{ backend_src_path }}/ {{ app_dir }}/

    - name: Install backend dependencies
      npm:
        path: "{{ app_dir }}"
        state: present
        production: false
        executable: /usr/bin/npm

    - name: Stop existing PM2 process (ignore errors)
      command: pm2 stop backend
      ignore_errors: true

    - name: Start backend with PM2
      command: pm2 start server.js --name backend
      args:
        chdir: "{{ app_dir }}"

    - name: Save PM2 process list
      command: pm2 save

    - name: Enable PM2 startup script
      command: pm2 startup systemd -u ec2-user --hp /home/ec2-user


