- name: Deploy backend
  hosts: backend
  become: true

  vars:
    jwt_secret_key: "{{ lookup('env', 'JWT_SECRET_KEY') }}"
    mongo_cloud_url: "{{ lookup('env', 'MONGO_DB_CLOUD_URL') }}"
    mongo_database: "{{ lookup('env', 'MONGO_DB_DATABASE') }}"

  tasks:

    - name: Copy backend code from app folder
      copy:
        src: app/
        dest: /var/www/backend/
        mode: "0755"

    - name: Create .env file
      template:
        src: env.j2
        dest: /var/www/backend/.env
        mode: "0600"

    - name: Install dependencies
      command: npm install
      args:
        chdir: /var/www/backend/

    - name: Build TypeScript (if TS project)
      command: npx tsc
      args:
        chdir: /var/www/backend/
      ignore_errors: yes   # JS backend ho to tsc error ignore

    - name: Start backend using PM2
      command: >
        pm2 restart backend ||
        pm2 start dist/index.js --name backend ||
        pm2 start index.js --name backend
      args:
        chdir: /var/www/backend/



