---
- name: Deploy Backend App on Amazon Linux 2023
  hosts: backend
  become: true

  vars:
    backend_src_path: "/home/ec2-user/Contact-Manager/backend"
    app_dir: "/app"

  tasks:

    # ---------------------------
    # Create /app directory
    # ---------------------------
    - name: Ensure /app directory exists
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: "0755"

    # ---------------------------
    # Install Prereqs for NodeSource
    # ---------------------------
    - name: Install dependencies
      package:
        name:
          - gcc-c++
          - make
          - openssl-devel
          - curl
        state: present

    # ---------------------------
    # Add NodeSource repo for Node.js 18 (AL2023 compatible)
    # ---------------------------
    - name: Add NodeSource repo for Node.js 18
      shell: |
        curl -fsSL https://rpm.nodesource.com/setup_18.x -o nodesource_setup.sh
        bash nodesource_setup.sh
      args:
        chdir: /tmp

    # ---------------------------
    # Install Node.js 18
    # ---------------------------
    - name: Install Node.js 18
      package:
        name: nodejs
        state: present

    # ---------------------------
    # Install PM2 globally
    # ---------------------------
    - name: Install PM2
      npm:
        name: pm2
        global: true
        executable: /usr/bin/npm

    # ---------------------------
    # Copy backend code to /app
    # ---------------------------
    - name: Copy backend code using rsync
      command: rsync -a --delete {{ backend_src_path }}/ {{ app_dir }}/

    # ---------------------------
    # Install project dependencies
    # ---------------------------
    - name: Install npm dependencies
      npm:
        path: "{{ app_dir }}"
        state: present
        production: false
        executable: /usr/bin/npm

    # ---------------------------
    # Stop existing pm2 service
    # ---------------------------
    - name: Stop old PM2 app if exists
      command: pm2 stop backend
      ignore_errors: true

    # ---------------------------
    # Start backend with PM2
    # ---------------------------
    - name: Start backend using PM2
      shell: pm2 start server.js --name backend
      args:
        chdir: "{{ app_dir }}"

    - name: Save PM2 process list
      command: pm2 save

    - name: Enable PM2 startup
      command: pm2 startup systemd -u ec2-user --hp /home/ec2-user



