- name: Deploy backend safely from GitHub
  hosts: backend
  become: true

  vars:
    app_user: roboshop
    repo_url: "https://github.com/AlankarSingh27/Contact-Manager.git"
    repo_branch: "main"
    tmp_dir: /tmp/Contact-Manager               # GitHub repo clone location
    app_dir: /app                               # final backend deploy folder
    jwt_secret_key: "{{ lookup('env', 'JWT_SECRET_KEY') }}"
    mongo_cloud_url: "{{ lookup('env', 'MONGO_DB_CLOUD_URL') }}"
    mongo_database: "{{ lookup('env', 'MONGO_DB_DATABASE') }}"

  tasks:

    # 0️⃣ Ensure git is installed
    - name: Ensure git is installed
      package:
        name: git
        state: present

    # 0️⃣ Ensure Node.js and npm are installed (Amazon Linux / RHEL)
    - name: Add NodeSource repo for Node.js 18
      shell: curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -

    - name: Install Node.js and npm
      package:
        name: nodejs
        state: present

    # 1️⃣ Ensure app user exists
    - name: Check if app user exists
      command: id {{ app_user }}
      register: out
      ignore_errors: true

    - name: Create app user if not exists
      user:
        name: "{{ app_user }}"
        shell: /bin/bash
      when: out.rc != 0

    # 2️⃣ Clone GitHub repo into /tmp
    - name: Clone GitHub repo into /tmp
      git:
        repo: "{{ repo_url }}"
        dest: "{{ tmp_dir }}"
        version: "{{ repo_branch }}"
        force: yes
      become_user: "{{ app_user }}"

    # 3️⃣ Ensure /app exists
    - name: Ensure /app directory exists
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'

    # 4️⃣ Copy backend folder content from repo to /app
    - name: Copy backend code from /tmp/Contact-Manager/backend to /app
      command: >
        rsync -a --delete {{ tmp_dir }}/backend/ {{ app_dir }}/
      become_user: "{{ app_user }}"

    # 5️⃣ Create .env file in /app
    - name: Create backend .env file
      template:
        src: env.j2
        dest: "{{ app_dir }}/.env"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0600"

    # 6️⃣ Install npm dependencies
    - name: Install backend npm dependencies
      command: npm install
      args:
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}"

    # 7️⃣ Build TypeScript (optional)
    - name: Build TypeScript
      command: npx tsc
      args:
        chdir: "{{ app_dir }}"
      ignore_errors: yes
      become_user: "{{ app_user }}"

    # 8️⃣ Start backend using PM2
    - name: Start backend using PM2
      command: >
        pm2 restart backend ||
        pm2 start dist/index.js --name backend ||
        pm2 start index.js --name backend
      args:
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}"
