- name: Deploy React Frontend (Production Grade)
  hosts: frontend
  become: true

  vars:
    app_user: roboshop
    app_dir: /app
    local_frontend_path: /home/ec2-user/contact-manager/client

  tasks:

    - name: Ensure roboshop user exists
      user:
        name: "{{ app_user }}"
        shell: /bin/bash"
        create_home: yes

    - name: Ensure /app directory exists
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ app_user }}"
        group: "{{ app_user }}"

    - name: Copy frontend code to server
      copy:
        src: "{{ local_frontend_path }}/"
        dest: "{{ app_dir }}/"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'

    - name: Install Node.js repo
      shell: curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -

    - name: Install Node.js
      yum:
        name: nodejs
        state: present

    - name: Install npm dependencies
      command: npm install
      args:
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}"

    - name: Build React App
      command: npm run build
      args:
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}"

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Copy Nginx template
      template:
        src: frontend.j2
        dest: /etc/nginx/conf.d/frontend.conf

    - name: Enable & Restart Nginx
      service:
        name: nginx
        state: restarted
        enabled: true

